# Generated by Django 4.1.5 on 2023-01-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_alter_post_date_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
