# Generated by Django 4.1.5 on 2023-01-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_po'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Po',
        ),
    ]
