# Generated by Django 4.1.5 on 2023-02-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_p'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Создать Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date',), 'verbose_name': 'Создать Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
