# Generated by Django 4.1.5 on 2023-02-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_category_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date',), 'verbose_name': 'Создать Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
