# Generated by Django 4.1.5 on 2023-02-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_category_rubric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='rubric',
        ),
    ]
